total_common_card_info = [[0, "rabbit", "command_warren", 2, "rabbit"],
               [1, "rabbit", "command_warren", 2, "rabbit"],
               [2, "rabbit", "sack", 1, "mouse"],
               [3, "rabbit", "money", 2, "rabbit"],
               [4, "rabbit", "favor", 3, "rabbit"],
               [5, "rabbit", "ambush", 0, "ambush"],
               [6, "rabbit", "better_burrow_bank", 2, "rabbit"],
               [7, "rabbit", "better_burrow_bank", 2, "rabbit"],
               [8, "rabbit", "dominance", 10, "point"],
               [9, "rabbit", "cobbler", 2, "rabbit"],
               [10, "rabbit", "cobbler", 2, "rabbit"],
               [11, "rabbit", "boot", 1, "rabbit"],
               [12, "rabbit", "root_tea", 1, "mouse"],
               [13, "mouse", "crossbow", 1, "fox"],
               [14, "mouse", "sword", 2, "fox"],
               [15, "mouse", "scouting_party", 2, "mouse"],
               [16, "mouse", "scouting_party", 2, "mouse"],
               [17, "mouse", "codebreakers", 1, "mouse"],
               [18, "mouse", "codebreakers", 1, "mouse"],
               [19, "mouse", "money", 2, "rabbit"],
               [20, "mouse", "dominance", 10, "point"],
               [21, "mouse", "root_tea", 1, "mouse"],
               [22, "mouse", "favor", 3, "mouse"],
               [23, "mouse", "boot", 1, "rabbit"],
               [24, "mouse", "sack", 1, "mouse"],
               [25, "mouse", "ambush", 0, "ambush"],
               [26, "fox", "hammer", 1, "fox"],
               [27, "fox", "stand_and_deliver", 3, "mouse"],
               [28, "fox", "stand_and_deliver", 3, "mouse"],
               [29, "fox", "tax_collector", 3, "all"],
               [30, "fox", "tax_collector", 3, "all"],
               [31, "fox", "tax_collector", 3, "all"],
               [32, "fox", "root_tea", 1, "mouse"],
               [33, "fox", "ambush", 0, "ambush"],
               [34, "fox", "sword", 2, "fox"],
               [35, "fox", "sack", 1, "mouse"],
               [36, "fox", "dominance", 10, "point"],
               [37, "fox", "favor", 3, "fox"],
               [38, "fox", "money", 2, "rabbit"],
               [39, "fox", "boot", 1, "rabbit"],
               [40, "bird", "sack", 1, "mouse"],
               [41, "bird", "sappers", 1, "mouse"],
               [42, "bird", "sappers", 1, "mouse"],
               [43, "bird", "boot", 1, "rabbit"],
               [44, "bird", "brutal_tactics", 2, "fox"],
               [45, "bird", "brutal_tactics", 2, "fox"],
               [46, "bird", "dominance", 10, "point"],
               [47, "bird", "sword", 2, "fox" ],
               [48, "bird", "ambush", 0, "ambush"],
               [49, "bird", "ambush", 0, "ambush"],
               [50, "bird", "armorers", 1, "fox"],
               [51, "bird", "armorers", 1, "fox"],
               [52, "bird", "crossbow", 1, "fox"],
               [53, "bird", "royal_claim", 4, "anything"]]

vagabond_quest_card_info = [[0, "root_tea", "money", "fox"],
                            [1, "boot", "sack", "fox"],
                            [2, "torch", "hammer", "fox"],
                            [3, "root_tea", "torch", "fox"],
                            [4, "root_tea", "boot", "fox"],
                            [5, "torch", "sword", "rabbit"],
                            [6, "sword", "sword", "rabbit"],
                            [7, "torch", "crossbow", "rabbit"],
                            [8, "torch", "root_tea", "rabbit"],
                            [9, "boot", "root_tea", "rabbit"],
                            [10, "torch", "crossbow", "mouse"],
                            [11, "torch", "sword", "mouse"],
                            [12, "boot", "sack", "mouse"],
                            [13, "boot", "boot", "mouse"],
                            [14, "sword", "sword", "mouse"]]

buildings_list_marquise = {"sawmill": {"cost": [0, 1, 2, 3, 3, 4], "VictoryPoints": [0, 1, 2, 3, 4, 5], "BonusCard":[0, 0, 0, 0, 0, 0]},
                            "workshop": {"cost": [0, 1, 2, 3, 3, 4], "VictoryPoints": [0, 2, 2, 3, 4, 5], "BonusCard":[0, 0, 0, 0, 0, 0]},
                            "recruiter": {"cost": [0, 1, 2, 3, 3, 4], "VictoryPoints": [0, 1, 2, 3, 3, 4], "BonusCard":[0, 0, 1, 0, 1, 0]}}