from item import Item
total_common_card_info = [[0, "rabbit", "command_warren", 2, "rabbit"],
               [1, "rabbit", "command_warren", 2, "rabbit"],
               [2, "rabbit", Item("sack"), 1, "mouse"],
               [3, "rabbit", Item("money"), 2, "rabbit"],
               [4, "rabbit", "favor", 3, "rabbit"],
               [5, "rabbit", "ambush", 0, "ambush"],
               [6, "rabbit", "better_burrow_bank", 2, "rabbit"],
               [7, "rabbit", "better_burrow_bank", 2, "rabbit"],
               [8, "rabbit", "dominance", 100, "dominance"],
               [9, "rabbit", "cobbler", 2, "rabbit"],
               [10, "rabbit", "cobbler", 2, "rabbit"],
               [11, "rabbit", Item("boot"), 1, "rabbit"],
               [12, "rabbit", Item("root_tea"), 1, "mouse"],
               [13, "mouse", Item("crossbow"), 1, "fox"],
               [14, "mouse", Item("sword"), 2, "fox"],
               [15, "mouse", "scouting_party", 2, "mouse"],
               [16, "mouse", "scouting_party", 2, "mouse"],
               [17, "mouse", "codebreakers", 1, "mouse"],
               [18, "mouse", "codebreakers", 1, "mouse"],
               [19, "mouse", Item("money"), 2, "rabbit"],
               [20, "mouse", "dominance", 100, "dominance"],
               [21, "mouse", Item("root_tea"), 1, "mouse"],
               [22, "mouse", "favor", 3, "mouse"],
               [23, "mouse", Item("boot"), 1, "rabbit"],
               [24, "mouse", Item("sack"), 1, "mouse"],
               [25, "mouse", "ambush", 0, "ambush"],
               [26, "fox", Item("hammer"), 1, "fox"],
               [27, "fox", "stand_and_deliver", 3, "mouse"],
               [28, "fox", "stand_and_deliver", 3, "mouse"],
               [29, "fox", "tax_collector", 3, "all"],
               [30, "fox", "tax_collector", 3, "all"],
               [31, "fox", "tax_collector", 3, "all"],
               [32, "fox", Item("root_tea"), 1, "mouse"],
               [33, "fox", "ambush", 0, "ambush"],
               [34, "fox", Item("sword"), 2, "fox"],
               [35, "fox", Item("sack"), 1, "mouse"],
               [36, "fox", "dominance", 100, "dominance"],
               [37, "fox", "favor", 3, "fox"],
               [38, "fox", Item("money"), 2, "rabbit"],
               [39, "fox", Item("boot"), 1, "rabbit"],
               [40, "bird", Item("sack"), 1, "mouse"],
               [41, "bird", "sappers", 1, "mouse"],
               [42, "bird", "sappers", 1, "mouse"],
               [43, "bird", Item("boot"), 1, "rabbit"],
               [44, "bird", "brutal_tactics", 2, "fox"],
               [45, "bird", "brutal_tactics", 2, "fox"],
               [46, "bird", "dominance", 100, "dominance"],
               [47, "bird", Item("sword"), 2, "fox" ],
               [48, "bird", "ambush", 0, "ambush"],
               [49, "bird", "ambush", 0, "ambush"],
               [50, "bird", "armorers", 1, "fox"],
               [51, "bird", "armorers", 1, "fox"],
               [52, "bird", Item("crossbow"), 1, "fox"],
               [53, "bird", "royal_claim", 4, "anything"]]

persistent_effects = ["command_warren", "cobbler", "scouting_party", "codebreakers", "stand_and_deliver", "tax_collector", "sappers", "brutal_tactics", "armorers", "dominance", "better_burrow_bank", "royal_claim"]
Immediate_non_item_effects = ["ambush", "favor"]


vagabond_quest_card_info = [[0, Item("root_tea"), Item("money"), "fox"],
                            [1, Item("boot"), Item("sack"), "fox"],
                            [2, Item("torch"), Item("hammer"), "fox"],
                            [3, Item("root_tea"), Item("torch"), "fox"],
                            [4, Item("root_tea"), Item("boot"), "fox"],
                            [5, Item("torch"), Item("sword"), "rabbit"],
                            [6, Item("sword"), Item("sword"), "rabbit"],
                            [7, Item("torch"), Item("crossbow"), "rabbit"],
                            [8, Item("torch"), Item("root_tea"), "rabbit"],
                            [9, Item("boot"), Item("root_tea"), "rabbit"],
                            [10, Item("torch"), Item("crossbow"), "mouse"],
                            [11, Item("torch"), Item("sword"), "mouse"],
                            [12, Item("boot"), Item("sack"), "mouse"],
                            [13, Item("boot"), Item("boot"), "mouse"],
                            [14, Item("sword"), Item("sword"), "mouse"]]

buildings_list_marquise = {"sawmill": {"VictoryPoints": [0, 1, 2, 3, 4, 5]},
                            "workshop": {"VictoryPoints": [0, 2, 2, 3, 4, 5]},
                            "recruiter": {"VictoryPoints": [0, 1, 2, 3, 3, 4]}}

sympathy_VPs = [0, 1, 1, 1, 2, 2, 3, 4, 4, 4]
eyrie_roost_VPs = [0, 1, 2, 3, 4, 4, 5]

eyrie_leader_config = {
    "Despot": ["move", "build"],
    "Builder": ["recruit", "move"],
    "Charismatic": ["recruit", "battle"],
    "Commander": ["move", "battle"],
}